spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BookShare
    username: ktomi87
    password: P4P8r&K1c
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop

