spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BookShare
    username: admin
    password: Adminpass&123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop

